driverClass=com.mysql.jdbc.Driver
jdbcUrl=jdbc\:mysql\://112.74.216.57\:3306/artcweb_admin_dev?useUnicode\=true&characterEncoding\=utf8&autoReconnect\=true
user=*
password=*


#jdbcUrl=jdbc\:mysql\://127.0.0.1\:3306/artcweb_admin?useUnicode\=true&characterEncoding\=utf8&autoReconnect\=true
#user=root
#password=root


maxActive=50
maxIdle=3
maxWait=1000
defaultAutoCommit=true
removeAbandoned=true
removeAbandonedTimeout=60
